### ISSUE TITLE
 '<' not supported between instances of 'Residue' and 'Residue'

### ISSUE THREAD

**Issue by mpperez3** [Valdes-Tresanco-MS/AutoDockTools_py3#2]
I have found an issue at:

MolKit\tree.py", line 940, in sort
    sorted(self.data)

Error:

 '<' not supported between instances of 'Residue' and 'Residue'

Using  the script prepare_flexreceptor4.py

How I can fix this issue?
Many thanks in advance.

**Comment by Valdes-Tresanco-MS** [comment]
Hi, thanks for report this issue.
Solved in https://github.com/Valdes-Tresanco-MS/AutoDockTools_py3/commit/574b70e6d1cdd6435d957fb5a0c7b666fd1d012b
Best!
