### ISSUE TITLE
mol2 parsing doesn't work

### ISSUE THREAD

**Issue by SolalAttias** [Valdes-Tresanco-MS/AutoDockTools_py3#4]
Line 116 of MolKit/mol2Parser.py
`            atmlines = [x.strip() for x in self.allLines[self.keysAndLinesIndices['@<TRIPOS>ATOM'][
`
Should be
`            atmlines = [x.split() for x in self.allLines[self.keysAndLinesIndices['@<TRIPOS>ATOM'][
`
Indeed, further in, build4LevelsTree expects atomlines to be a list of list of strings, and not a list of strings

**Comment by Valdes-Tresanco-MS** [comment]
Could you create a PR?
