### ISSUE TITLE
Please include quick example of how to run prepare_ligand4.py

### ISSUE THREAD

**Issue by sibo** [Valdes-Tresanco-MS/AutoDockTools_py3#7]
After installing your code with pip as described in the README file, how does one use prepare_ligand4.py?

**Comment by Valdes-Tresanco-MS** [comment]
I have added the commonly used script as console_script. So, you can use them simply by typing their name in the terminal after reinstalling ADT3
Console scripts
- prepare_ligand4
- prepare_receptor4
- prepare_gpf4
- prepare_dpf4
- prepare_flexreceptor4
- prepare_covalent_flexres
- AutoLigand

Examples:
```bash
prepare_receptor4 -r pdb_file -o outputfilename -A checkhydrogens 
prepare_ligand4 -l pdb_file -v
```
Note that the executables do not end in `.py`

Note: Any other script contained in the AutoDockTools/Utilities folder must be executed as:
```bash
python /path/to/AutoDockTools/Utilities/script.py
```
Example:
In my case, I have ADT3 installed in a conda environment
```
python /home/mario/miniconda3/envs/ADT3/lib/python3.11/site-packages/AutoDockTools/Utilities24/rotate_molecule.py
```
